engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
        enabled: true
        config:
          languages:
          - ruby
          - javascript
          - python
          - php
ratings:
   paths:
   - "**/**"
